
logging:
  level:
    root: warn
    com.ico: info
    com.ico.api: info
    org.hibernate.type.descriptor.sql: trace
    com.amazonaws.util.EC2MetadataUtils: error
    # 로컬 실행 시 aws 환경이 아니라 에러 로그 출력된다.
    # 배포하여 aws 환경에서는 문제가 없기 때문에 실행 시 로그를 감춘다.

server:
#  address: 192.168.100.166 프론트와 로컬 연결
  port: 8081
#  domain 설정 시 로컬로 실행하여 같은 네트워크에서 해당 주소로 접근할 수 있다.
#  domain: http://127.0.0.1
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728

spring:
  profiles:
    active: dev
    group:
      dev:
        - db-dev
      local:
        - db-local
    include:
      - db
      - login
      - aws
      - redis

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      # create(new table), update(add new column), none(nothing)
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always
      continue-on-error: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  dependencies:
    net.nurigo:
      java-sdk: 3.5