# 공통 설정
spring:
  # Security 및 JWT 설정
  security:
    jwt:
      header: Authorization
      # linux 환경에서 아래 코드 입력하면 키 생성됨
      # echo 'silvernine-tech-spring-boot-j#wt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWoKd3QtdHV0b3JpYWwtc2VjcmV0LXNpbHZlcm5pbmUtdGVjaC1zcHJpbmctYm9vdC1qd3QtdHV0b3JpYWwtc2VjcmV0Cg==
