
logging:
  level:
    root: warn
    com.ico: info
    com.ico.api: info
    org.hibernate.type.descriptor.sql: trace

server:
  port: 8082
  #  domain: http://127.0.0.1
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728

spring:
  profiles:
    active: dev
    group:
      dev:
        - db-dev
      local:
        - db-local
    include:
      - db
      - login

  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      # create(new table), update(add new column), none(nothing)
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true

