
logging:
  level:
    root: warn
    com.ico: info
    com.ico.api: info
    org.hibernate.type.descriptor.sql: trace

server:
  port: 8082
  #  domain: http://127.0.0.1
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728

spring:
  profiles:
    active: local
    group:
      dev:
        - db-dev
      local:
        - db-local
    include:
      - db

  batch:
    job:
      names: ${job.name:NONE}
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      # create(new table), update(add new column), none(nothing)
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always              # \uD56D\uC0C1 SQL \uCD08\uAE30\uD654
      continue-on-error: true   # SQL \uCD08\uAE30\uD654 \uC911 \uC624\uB958\uAC00 \uBC1C\uC0DD\uD574\uB3C4 \uACC4\uC18D \uC2E4\uD589

